name = "WaterLilyPreCICE"
uuid = "b93379c7-902c-434f-b41d-dc1459e7cb02"
authors = ["marinlauber <marinlauber@tudelft.nl>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CirculatorySystemModels = "4211d73e-f4e8-40c4-b600-92e4b82f0e1a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
ParametricBodies = "06905c2e-4b4a-4765-8bb9-c6b6b2b99b1d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PreCICE = "57fbd4af-5cc3-4712-aac0-6930e7658184"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WaterLily = "ed894a53-35f9-47f1-b17f-85db9237eebd"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
Reexport = "^1.2.2"
StaticArrays = "^1.1.0"
julia = "1.9"
WaterLily = "^1.2.0"
ParametricBodies = "^0.1.0"